{% set version = "0.0.2" %}
{% set proj_version = ">=9.0.0" %}

package:
  name: csrspy
  version: {{ version }}

source:
  path: ..

build:
  number: 0
#  script: python -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.16
  host:
    - python {{ python }}
    - proj {{ proj_version }}
    - pip
  run:
    - python {{ python }}

test:
  imports:
    - csrspy

about:
  home: https://github.com/HakaiInstitute/reproject_csrs
  license: MIT
  summary: 'Python library to convert coordinates from various ITRF realizations to NAD83(CSRS).'
  description: |
    A Python library to convert coordinates from various ITRF realizations to NAD83(CSRS).
  dev_url: https://github.com/HakaiInstitute/reproject_csrs
  doc_url: https://github.com/HakaiInstitute/reproject_csrs
  doc_source_url: https://github.com/HakaiInstitute/reproject_csrs/blob/master/README.md